import { GetSearchItemProps } from "../Serves/SearchServes/models/GetSearchItem";

const fakeSearchImtes: Array<GetSearchItemProps> = [
  { id: "1", name: "iPhone" },
  { id: "2", name: "iPhone 3G" },
  { id: "3", name: "iPhone 3GS" },
  { id: "4", name: "iPhone 4" },
  { id: "5", name: "iPhone 4s" },
  { id: "6", name: "iPhone 5" },
  { id: "7", name: "iPhone 5c" },
  { id: "8", name: "iPhone 5s" },
  { id: "9", name: "iPhone 6" },
  { id: "10", name: "iPhone 6 Plus" },
  { id: "11", name: "iPhone 6s" },
  { id: "12", name: "iPhone 6s Plus" },
  { id: "13", name: "iPhone SE (1st generation)" },
  { id: "14", name: "iPhone 7" },
  { id: "15", name: "iPhone 7 Plus" },
  { id: "16", name: "iPhone 8" },
  { id: "17", name: "iPhone 8 Plus" },
  { id: "18", name: "iPhone X" },
  { id: "19", name: "iPhone XR" },
  { id: "20", name: "iPhone XS" },
  { id: "21", name: "iPhone XS Max" },
  { id: "22", name: "iPhone 11" },
  { id: "23", name: "iPhone 11 Pro" },
  { id: "24", name: "iPhone 11 Pro Max" },
  { id: "25", name: "iPhone SE (2nd generation)" },
  { id: "26", name: "iPhone 12" },
  { id: "27", name: "iPhone 12 mini" },
  { id: "28", name: "iPhone 12 Pro" },
  { id: "29", name: "iPhone 12 Pro Max" },
  { id: "30", name: "iPhone 13" },
  { id: "31", name: "iPhone 13 mini" },
  { id: "32", name: "iPhone 13 Pro" },
  { id: "33", name: "iPhone 13 Pro Max" },
  { id: "34", name: "iPhone SE (3rd generation)" },
  { id: "35", name: "iPhone 14" },
  { id: "36", name: "iPhone 14 Plus" },
  { id: "37", name: "iPhone 14 Pro" },
  { id: "38", name: "iPhone 14 Pro Max" },
  { id: "39", name: "iPhone 15" },
  { id: "40", name: "iPhone 15 Plus" },
  { id: "41", name: "iPhone 15 Pro" },
  { id: "42", name: "iPhone 15 Pro Max" },
];

export default fakeSearchImtes;
